export const Userdata=[
  {
    useravatar:'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    username:'法海',
    userid:'0',
    userphone:13588888888,
    usersex:'男',
    userrate:'黄金会员'
  },
  {
    useravatar:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    username:'洛河图',
    userid:'1',
    userphone:135777877777,
    usersex:'男',
    userrate:'黄金会员'
  },
  {
    useravatar:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    username:'格雷福斯',
    userid:'2',
    userphone:13988888888,
    usersex:'男',
    userrate:'黄金会员'
  },
  {
    useravatar:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    username:'凯尔',
    userid:'8',
    userphone:13588888888,
    usersex:'女',
    userrate:'黄金会员'
  },
  {
    useravatar:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    username:'该隐',
    userid:'4',
    userphone:13588888868,
    usersex:'男',
    userrate:'黄金会员'
  }
]
export const Employeedata=[
  {
    employeeavatar:'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
    employeename:'法海',
    employeeid:0,
    employeephone:13588888888,
    employeesex:'男',
    employeedate:'2017.9.8',
    employeerate:5
  },
  {
    employeeavatar:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    employeename:'洛河图',
    employeeid:1,
    employeephone:135777877777,
    employeesex:'男',
    employeedate:'2017.9.8',
    employeerate:3
  },
  {
    employeeavatar:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    employeename:'格雷福斯',
    employeeid:9,
    employeephone:13988888888,
    employeesex:'男',
    employeedate:'2017.9.8',
    employeerate:3
  },
  {
    employeeavatar:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    employeename:'凯尔',
    employeeid:3,
    employeephone:13588888888,
    employeesex:'女',
    employeedate:'2017.9.8',
    employeerate:3
  },
  {
    employeeavatar:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    employeename:'该隐',
    employeeid:4,
    employeephone:13588888868,
    employeesex:'男',
    employeedate:'2017.9.8',
    employeerate:3
  }
];
export const Fooddata=[
  {
    foodimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    foodname:'蚂蚁上树',
    foodprice:39,
    foodtype:'炒菜',
    foodid:0
  },
  {
    foodimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    foodname:'蚂蚁上树',
    foodprice:39,
    foodtype:'甜点',
    foodid:1
  },
  {
    foodimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    foodname:'蚂蚁上树',
    foodprice:39,
    foodtype:'主食',
    foodid:2
  },
  {
    foodimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    foodname:'蚂蚁上树',
    foodprice:39,
    foodtype:'汤',
    foodid:3
  },
  {
    foodimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    foodname:'蚂蚁上树',
    foodprice:39,
    foodtype:'火锅',
    foodid:4

  },
  {
    foodimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    foodname:'蚂蚁上树',
    foodprice:39,
    foodtype:'饮料',
    foodid:5

  }
];
export const Materialdata=[
  {
    materialimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    materialname:'牛肉',
    materialtype:'肉类',
    materialcount:'30斤',
    materialprovider:'老马',
    materialid:0
  },
  {
    materialimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    materialname:'猪肉',
    materialtype:'肉类',
    materialcount:'30斤',
    materialprovider:'老马',
    materialid:1
  },
  {
    materialimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
    materialname:'娃娃菜',
    materialtype:'蔬菜',
    materialcount:'30斤',
    materialprovider:'老马',
    materialid:2
  },  {
      materialimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
      materialname:'芒果',
      materialtype:'水果',
      materialcount:'30斤',
      materialprovider:'老马',
      materialid:3
    },
    {
      materialimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
      materialname:'胡椒粉',
      materialtype:'调味品',
      materialcount:'3瓶',
      materialprovider:'老马',
      materialid:4
    },  {
        materialimg:'http://tupian.enterdesk.com/2014/mxy/11/10/1/6.jpg',
        materialname:'大米',
        materialtype:'主食',
        materialcount:'30斤',
        materialprovider:'老马',
        materialid:5
      }
];
export const Roomlist=[
  {
    key:0,
    type:'1001',
    date:'2017-7-5',
    user:'老马',
    ps:'无'
  },
  {
    key:1,
    type:'1002',
    date:'2017-7-5',
    user:'老马',
    ps:'无'
  },
  {
    key:2,
    type:'1001',
    date:'2017-7-5',
    user:'老马',
    ps:'无'
  },{
    key:3,
    type:'1001',
    date:'2017-7-5',
    user:'老马',
    ps:'无'
  },{
    key:4,
    type:'1001',
    date:'2017-7-5',
    user:'老马',
    ps:'无'
  },{
    key:5,
    type:'1002',
    date:'2017-7-5',
    user:'老马',
    ps:'无'
  }
];
export const Profitdata=[['1','8.34','0.42'],['2','5.62','0.36'],['3','2.82','0.16'],['4','7.62','0.37']];
